module.exports={
    db:{
        "database":"e-commerace",
        "username":"postgres",
        "password":"1111",
        "host":"localhost",
        "port":5432,
        "dialect":"postgres"
    },
    "jwtSecret":"aaaa"
}